In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
encoder = OneHotEncoder()

In [3]:
data = {'Fruit' : ['Apple', 'Banana', 'Orange', 'Grapes', 'Mango'],
        'Color' : ['Red', 'Yellow', 'Orange', 'Green', 'Yellow']
}

In [4]:
df = pd.DataFrame(data)

In [5]:
encoder_color = encoder.fit_transform(df[['Color']]).toarray()

In [7]:
encoder_df = pd.DataFrame(encoder_color, columns=encoder.get_feature_names_out(['Color']))

In [8]:
pd.concat([df,encoder_df], axis=1)

    Fruit   Color  Color_Green  Color_Orange  Color_Red  Color_Yellow
0   Apple     Red          0.0           0.0        1.0           0.0
1  Banana  Yellow          0.0           0.0        0.0           1.0
2  Orange  Orange          0.0           1.0        0.0           0.0
3  Grapes   Green          1.0           0.0        0.0           0.0
4   Mango  Yellow          0.0           0.0        0.0           1.0

In [9]:
encoder_df

   Color_Green  Color_Orange  Color_Red  Color_Yellow
0          0.0           0.0        1.0           0.0
1          0.0           0.0        0.0           1.0
2          0.0           1.0        0.0           0.0
3          1.0           0.0        0.0           0.0
4          0.0           0.0        0.0           1.0