In [ ]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

In [ ]:
data = [10,20,30,40,50]
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#we can change the index of the series to custom index

In [ ]:
data = [10,20,30,40,50]
custom_index = ['a','b','c','d','e']
s = pd.Series(data,index=custom_index)
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
s['e']

np.int64(50)

In [ ]:
res = s+5
res

a    15
b    25
c    35
d    45
e    55
dtype: int64

In [ ]:
a={
    'Name' : ['A','B','C','D'],
    'Age' : [20,21,22,23],
    'City' : ['W','X','Y','Z']
}

In [ ]:
df = pd.DataFrame(a)
df

  Name  Age City
0    A   20    W
1    B   21    X
2    C   22    Y
3    D   23    Z

In [ ]:
df['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: str

In [ ]:
df.loc[3]

Name     D
Age     23
City     Z
Name: 3, dtype: object

In [ ]:
df = pd.read_csv('demo_dataset.csv')
df

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.head()

      name   age         city  salary  weight
0    Alice  25.0     New York   55000      58
1      Bob  30.0  Los Angeles   62000      72
2  Charlie  28.0      Chicago   60000      68
3    David  35.0      Houston   72000      80
4     Emma  27.0      Phoenix   58000      55

In [ ]:
#To print the number of rows we can give manually

In [ ]:
pd.options.display.max_rows = 5

In [ ]:
df

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   age     9 non-null      float64
 2   city    10 non-null     str
 3   salary  10 non-null     int64
 4   weight  10 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 528.0 bytes

In [ ]:
df.describe()

             age   salary  weight
count   9.000000     10.0    10.0
mean   29.444444  64900.0    68.2
...          ...      ...     ...
75%    32.000000  69250.0    77.0
max    35.000000  85000.0    85.0

[8 rows x 3 columns]

In [ ]:
df.shape

(10, 5)

In [ ]:
# To identify the NAN values in the dataset we can use the following command

In [ ]:
df.isna().sum()

name      0
age       1
city      0
salary    0
weight    0
dtype: int64

In [ ]:
# to chnage the NAN value we can use the following command

In [ ]:
df["age"].fillna(20, inplace=True)
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20060\2757973175.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"].fillna(20, inplace=True)

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.isna().sum()

name      0
age       0
city      0
salary    0
weight    0
dtype: int64

In [ ]:
df.fillna({"age": 20},inplace=True)

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.fillna(20, inplace=True)

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   age     10 non-null     float64
 2   city    10 non-null     str
 3   salary  10 non-null     int64
 4   weight  10 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 528.0 bytes

In [ ]:
x = df["age"].mean()

In [ ]:
df.fillna({"age":x}, inplace=True)
df

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.loc[5]

name             Frank
age               25.0
city      Philadelphia
salary           85000
weight              85
Name: 5, dtype: object

In [ ]:
q = df["age"].mode()[0]

In [ ]:
df.fillna({"age":q}, inplace=True)

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.drop_duplicates(inplace=True)
df

        name   age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df.rename(columns={"age":"Age"}, inplace=True)
df

        name   Age         city  salary  weight
0      Alice  25.0     New York   55000      58
1        Bob  30.0  Los Angeles   62000      72
..       ...   ...          ...     ...     ...
8   Isabella  26.0       Dallas   59000      52
9       Jack  33.0     San Jose   70000      78

[10 rows x 5 columns]

In [ ]:
df['gender']=['M','F','M','M','F','M','M','F','M','M']
df

        name   Age         city  salary  weight gender
0      Alice  25.0     New York   55000      58      M
1        Bob  30.0  Los Angeles   62000      72      F
..       ...   ...          ...     ...     ...    ...
8   Isabella  26.0       Dallas   59000      52      M
9       Jack  33.0     San Jose   70000      78      M

[10 rows x 6 columns]

In [ ]:
g = df.groupby("gender")["Age"].mean()
g

gender
F    28.666667
M    29.142857
Name: Age, dtype: float64

In [ ]:
df.corr()

ValueError: could not convert string to float: 'Alice'